VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  config.vm.synced_folder ". " "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master.k8s"
    master.vm.network :private_network, ip: "192.168.56.2"
  end
  
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker.k8s"
    worker.vm.network :private_network, ip: "192.168.56.3"
  end
  
end

