VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/bullseye64"
  config.ssh.insert_key = false
  config.vm.synced_folder ". " "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 2012
    v.linked_clone = true
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master.k8s"
    master.vm.network :private_network, ip: "192.168.56.2"
  end
  
  (1..3).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.hostname = "worker-#{i}.k8s"
      worker.vm.network :private_network, ip: "192.168.56.#{i + 2}"
    end
  end  
end

